<?php



$titremars1948a="AT THE GATES OF JINZHOU";
$textemars1948a="
The People's Liberation Army, after months of campaign, is at the gates of Jinzhou.<br>
Should this strategic position be taken, the road to Peking would be open and the communists would overrun the south.<br>
The town and its surroundings are strong and valiantly defended, but observers noticed that the PLA is now on equal footing with the National Revolutionary Army: this a real deluge of shells that prepares the final assault on the Kuomintang's positions.

";

$titremars1948a1="AT THE GATES OF JINZHOU";
$textemars1948a1="";
$textemars1948aa="
Days after days, the brave defenders of Jinzhou drive back the communist assault waves.<br>
The heroic resistance of the garrison managed to convince Chiang Kai-shek to send sizable reinforcements to counterattack and clear the town.<br>
The People's Liberation Army is constrained to withdraw with high casualties.

";
$textemars1948ab="
Days after days, the brave defenders of Jinzhou are beaten down by the communist shells.<br>
Reinforcements will never come and a triumphant PLA finally overruns the Liaoning province.

";



$choix1mars1948a="This battle is of utmost importance";
$choix1mars1948atitle="What will the outcome be?";


// EVT B

$titremars1948b="THE CURÉE";
$textemars1948b="
Everything has gone wrong for the nationalists in China: strategic regions and major towns are captured one after another.<br>
Counterattacks launched by the National Revolutionary Army failed because of betrayals within their own ranks: entire units defect or are surrounded.<br>
Will the Kuomintang ever survive such a succession of disasters?

";

$choix1mars1948b="This is a huge setback";
$choix1mars1948btitle="This civil war is coming to an end";


$titremars1948b1="THE CURÉE";
$textemars1948b1="
Following each of its impressive victories, the People's Liberation Army seizes more and more heavy weapons and enlists the captured nationalist conscripts.<br>
It seems that a communist victory in the Chinese civil war is now inevitable... 

";


// EVT C

$titremars1948c="THE CZECH COUP";
$textemars1948c="
Tension is high within the Czechoslovak coalition government which includes communists.<br>
		These ones are in charge of the Home Office and are putting their men at key positions.<br>
		Faced with a fait accompli, democrat ministers attempt to trigger a political crisis through joint resignation.<br>
		The communists are ready to fill the empty positions thanks to the pressure generated by large street protest marches.
		<br>Washington monitors the Czechoslovak situation with anxiety: a coup de force would spell the end of the understanding between the two great victors of WW2. 
		

";

$choix1mars1948c="Let us seize power!";
$choix1mars1948ctitle="Czechoslovakia falls into your camp, pro-US oppositions are suppressed and tension rises sharply";

$choix2mars1948c="Let us wait for another opportunity";
$choix2mars1948ctitle="Decreases stalinism and Czechoslovakia's stability";

$titremars1948c1="THE CZECH COUP";
$textemars1948c1="
Taking advantage of President Beneš' weakness, stroke a few days ago, communist and social democrat parties seize power.<br>
No sooner are they in place than a hunt for opponents is launched where hundreds of them are arrested.<br>
Worker militias hold the street and nothing can save the Czechoslovak bourgeois republic.

";

$titremars1948c2="A NEW GOVERNMENT";
$textemars1948c2="
An umpteenth coalition government is eventually formed.<br>
Communists are still part of it but seems to be open to some compromises...<br>
After screening out a number of potential candidates, deputy Milada Horáková has been called to run this dysfunctional assembly.<br>
How long will this new government stand? 

";

// EVT D

$titremars1948d="WE NEED TO BRING BACK LENINGRAD INTO LINE";
$textemars1948d="
Leningrad emerged from WW2 haloed with the glory of its heroic resistance against the Nazis.<br>
Local communist party rulers are brilliant and ambitious...<br>
That makes a lot of reason to distrust these Leningard people.<br>
Who knows what they are up to.<br>
It is time to do some on-site investigation and purge the party of its bad elements.

";

$choix1mars1948d="Let us purge massively (prestige -25)";
$choix1mars1948dtitle="Increases stalinism";

$choix2mars1948d="Let us purge in a targeted manner (no more than 500 persons)";
$choix2mars1948dtitle="This bout of softness will harm you: decreases stalinism";

$titremars1948d1="THE ACHE WAS DEEP";
$textemars1948d1="
Over 2,000 traitors and schemers were arrested.
This could not have waited longer!
<br>
Indeed, the entire Leningrad society was involved in anti-Soviet activities, from factories directors to academia circles.<br>
Executives from Moscow, true communists in line with the party will ensure continuity and bring back Leningrad region in line. 

";

$titremars1948d2="VENALITY PREVAILS IN LENINGRAD";
$textemars1948d2="
Because of our lack of revolutionary discipline, we let bourgeois values infest the party's executives in Leningrad...<br>
It would not be surprising to see counterrevolutionary groups emerging from region.<br>
";

// EVT E

$titremars1948e="THE CZECH COUP";
$textemars1948e="
Tension is high within the Czechoslovak coalition government which includes communists.<br>
These ones are in charge of the Home Office and are putting their men at key positions.<br>
Faced with a fait accompli, democrat ministers attempt to trigger a political crisis through mass resignation.<br>
The communists are ready to fill the empty positions thanks to the pressure generated by large street protest marches.
<br> We monitor the Czechoslovak situation with anxiety: a coup de force would spell the end of the understanding between the two great victors of WW2.. 
";

$choix1mars1948e="The free world holds its breath...";
$choix1mars1948etitle="This will end badly: Czechoslovakia falls into the Soviet camp, pro-US oppositions are suppressed and tension rises sharply";

$titremars1948e1="THE CZECH COUP";
$textemars1948e1="
Taking advantage of President Beneš' weakness, stroke a few days ago, communist and social democrat parties seize power.<br>
No sooner are they in place than a hunt for opponents is launched where hundreds of them are arrested.<br>
Worker militias hold the street and nothing can save the Czechoslovak democracy.

";



// EVENT F

$titremars1948f="THE ITALIAN GENERAL ELECTIONS";
$textemars1948f="
The Czechoslovak precedent demonstrated that a democracy with a powerful communist party could fall into marxism.<br>
		The Italian general elections embody a real danger as Moscow is pouring millions of dollars in the peninsula to influence the outcomes of the polls.<br>
		We should do exactly the same.<br>
		Threat, slander, blackmail, corruption and funding foreign parties are probably not what we usually describe as democratic methods...<br>
		But do we really have the choice?
";


$choix1mars1948f="Let us influence these elections (-$10 et -10 prestige)";
$choix1mars1948ftitle="Danger will be passed but this country gains the trait Corruption";

$choix2mars1948f="Let the best ones win!";
$choix2mars1948ftitle="The Italian stability decreases, the country loses the trait Corruption and communists have a very low chance to win the elections";

$titremars1948f1="CLEAR VICTORY OF THE CHRISTIAN DEMOCRACY";
$textemars1948f1="
The communist-socialist coalition is clearly behind the Christian Democracy party.<br>
This country was saved from the communist temptation... for now.
";

$titremars1948f2="A CHAMBER OF DEPUTIES WITHOUT MAJORITY";
$textemars1948f2="
It is difficult to say who will be able to rule this country!<br>
Circumstancial majorities appear and disappear following events and small parties like the National Bloc and the Socialist Unity often act as arbitrators of the votes.<br>
In order to maintain relative stability, the Italian government tries to have good relations with both Washington and Moscow - making Italy a de facto non aligned country.
";

// EVT G

$titremars1948g="A HERETIC";
$textemars1948g="
Marshal Tito has a growing tendency to take liberties with Moscow, forgetting what Yugoslavia owes to the Red Army.
		He takes initiatives without consulting us.<br>
		He currently undertakes to build a Balkan socialist federation with Albania and even Bulgaria, of course without our agreement to his projects.<br>
		It may be time to call him to order!
";

$choix1mars1948g="Let us exclude the Yugoslavs from the Cominform";
$choix1mars1948gtitle="Severely deteriorates your relations with Yugoslavia";

$choix2mars1948g="If we cannot reason with him, let us support him!";
$choix2mars1948gtitle="You will lose the Zhadnov Doctrine effects, decrease stalinism and will likely increase guerrilla in Greece.";

$choix3mars1948g="Tito is THE problem: let us poison him!";
$choix3mars1948gtitle="An action with a very random result.";

$titremars1948g1="A HERETIC";
$textemars1948g1="
Yugoslavia has just been excluded from the Cominform: let us see how they manage without the support of the communist world.<br><br>
<span style=\"font-style:italic;\">The country becomes non aligned and its relations with the USSR deteriorate to their lowest level.</span>
";

$titremars1948g2="A VISIONARY";
$textemars1948g2="
Under the Yugoslavian energic impetus, an expansionist communism develops in the Balkans.<br>
Moscow keeps up with what is going on and the other Eastern countries realise they can follow their own path toward communism.<br>
";

$titremars1948g3="A CONVICT";
$textemars1948g3="
Our secret services attempted to murder Tito and...<br><br>
";



$textemars1948gb="Civil war in Greece resumes, funded, supplied and armed by Yugoslavia.";
$textemars1948gc="succeed! <br><br>
Life in the mountains drained this Nazi-fighter hero's body.<br>
Marshal Tito passed away before his 60th birthday, brought down by a coronary.<br>
Following spectacular national funerals, the Yugloslav central committee reaffirmed its commitment to Cominform activities and its eternal friendship with the USSR.
";
$textemars1948gd="fail<br><br>
Yugoslavia will pursue its own foreign policy in the Balkans.<br>
Other Eastern countries realise they can follow their own path toward communism.<br>
";
$textemars1948ge="fail!<br><br>
However, Tito got the message.<br>
He will keep a low profile from now on...<br>
";


// EVENT H

$titremars1948h="THE CANNONS OF VICTORY";
$textemars1948h="
The fortune of war in China could tilt toward the communists, provided they own heavy weapons...<br>
It is probably time to accelerate the end of this endless civil war.<br>
Manchu railways could be used to deliver massive aid to the People's Liberation Army - including surpluses from the US lend-lease and cannons.<br>
Our regional allies could also be mobilised to militarily support the Chinese communists.<br>
";

$choix1mars1948h="Let us help the Chinese communists (-$50)";
$choix1mars1948htitle="Dispatches North Korean volunteers if North Korea is a People's Republic, equips guerrilla with heavy weapons and improves your relations with the communists";

$choix2mars1948h="Let the best win!";
$choix2mars1948htitle="Improves your relations with the nationalists";

$titremars1948h1="THE CANNONS OF VICTORY";
$textemars1948h1="
Cannons and tanks, most of them Japanese or American-made, massively reinforce the communist armies: they are now sufficiently equipped to capture the nationalist strongholds.<br>
";

$textemars1948ha="200,000 Korean volunteers joined the People's Liberation Army's ranks: the time for general offensive is now!";

$titremars1948h2="A RUSTIC ARMY";
$textemars1948h2="
Chinese communists will keep fighting with make-shift compromises.
<br> This civil war will last a bit longer.
";


// EVENT i

$titremars1948i="DO WE NEED A DEUTSCHE MARK?";
$textemars1948i="
Germany is divided in occupation zones and still riddled with many problems.<br>
		It would need a monetary reform to get rid of excess liquidity, eliminate black market and revitalise production. <br>
		The USSR will never accept such a reform and the Potsdam agreement states that these questions are under collective sovereignty.
		<br>Should we introduce a new currency in Allied zones at the risk of offending the Soviets?
";

$choix1mars1948i="Let us enforce the Deutsche Mark.";
$choix1mars1948ititle="Increases West German stability and improves GDR relations with the USA but could trigger a crisis with the Soviets";

$choix2mars1948i="Let us not provoke the Russians!";
$choix2mars1948ititle="Decreases DEFCON and West German stability";

$titremars1948i1="THE DEUTSCHE MARK ADOPTED";
$textemars1948i1="
This new currency marks a new beginning and will help the German people to look to the future with confidence!<br>
<span style=\"font-style:italic;\">West German stability icnreases as well as their relations with you</span>
";

$titremars1948i2="A BOOM IN BLACK MARKET ACTIVITIES";
$textemars1948i2="
Inflation and development of black market trading prevent a quick revitalisation of the German economy.<br>
Resourcefulness and maffias are kings of the streets.
<span style=\"font-style:italic;\">Decreases West German stability, the country gains the trait \"Corruption\" but DEFCON decreases</span>
";



$titremars1948j="THE BERLIN BLOCKADE";
$textemars1948j="
The Soviets cut all rail and river traffic to West Berlin and are putting the city under complete blockade. 
<br>They protest against the adoption of the new currency.<br>
			The people of Berlin, taken hostage, could rapidly lack of food and electricity.
";

$choix1mars1948j="Let us supply Berlin through the airs!(-$10/month)";
$choix1mars1948jtitle="Will trigger a showdown with the Soviets.";

$choix2mars1948j="Let us yield to the Soviets demands (Prestige -25)";
$choix2mars1948jtitle="End of the crisis and loss of 25 prestige points.";


$titremars1948j1="SUPPLYING BERLIN";
$textemars1948j1="
It is with determination and reactivity that we set up an airlfit, and the first aeroplanes are already landing at Tempelhof airport.<br>
We must supply over 2 million inhabitants through the airs!<br>
This is a real logistic prowess we are achieveing.<br>
However, the people of Berlin will have to make sacrifices and adapt to electricity and heating shortages: this should not pose any major problem considering the good summer.
";

$titremars1948j2="WE BACK OFF IN BERLIN";
$textemars1948j2="
Saving the population of Berlin overrides any ideological consideration.<br>
We made the right choice in abandoning the Deutsche Mark and started talks with the Soviets on monetary issues.<br>
";


// EVT K

$titremars1948k="BLOCKADING BERLIN?";
$textemars1948k="
Germany is divided in occupation zones and still riddled with many problems.<br>
		The Westerners created a new German currency without consulting us.<br>
		The Potsdam agreement states that these questions are under collective sovereignty!<br>
		They are now trying to import this currency in West Berlin.<br>
";

$choix1mars1948k="This shall not be! Let us blockade Berlin! (-$10/month)";
$choix1mars1948ktitle="Will trigger a showdown with the Americans and increases DEFCON.";

$choix2mars1948k="Let them proceed (Prestige -25)";
$choix2mars1948ktitle="You avoid troubles and lose 25 prestige points + decreases DEFCON";

$titremars1948k1="BLOCKADING BERLIN?";
$textemars1948k1="
We cut all rail and river traffic to West Berlin and are putting the city under complete blockade. 
<br>
	The people of Berlin, taken hostage, could quickly lack food and electricity.
	<br> The USA should rapidly back off.
";

$titremars1948k2="A NEW CURRENCY";
$textemars1948k2="
The new currency is a great success and has been seen in use in East Berlin.<br>
We closely monitor the changing monetary situation in Germany.
<span style=\"font-style:italic;\">Increases West German stability and its relations with the USA</span>
";

$titremars1948l="AN AIRLIFT FOR BERLIN";
$textemars1948l="
The USA organise an airlift to supply Berlin!<br>
This will probably be insufficient though.<br>
Our agents reported that some 60 Superfortress B-29 were deployed in Great Britain.<br>
Will these aeroplanes take part in the airlift or are they loaded with atomic bombs?
";

$choix1mars1948l="Let us give way to the capitalists demands (Prestige -25)";
$choix1mars1948ltitle="End of the crisis and loss of 25 prestige points.";

$choix2mars1948l="Let us maintain the blockade";
$choix2mars1948ltitle="We will see who yields first";

$titremars1948l1="WE LIFT THE BLOCKADE";
$textemars1948l1="
We gave up faced with the American determination.<br>
The new currency is a great success and has been seen in use in East Berlin.<br>
We closely monitor the changing monetary situation in Germany.
<span style=\"font-style:italic;\">Increases West German stability and its relations with the USA</span>
";

$titremars1948l2="THE BLOCKADE GOES ON";
$textemars1948l2="
Time is on our side: the Americans will not be able to supply over 2 million people via an airlift on the long term...
";

// EVENT M

$titremars1948m="THE GREAT PLAN FOR THE TRANSFORMATION OF NATURE";
$textemars1948m="
It is time to develop the European steppe and bend nature to our will.<br>
		Joseph Stalin wants an ambitious plan to transform the country through vast irrigation works, planting massive forests and gigantic hydraulic projects to be launched as soon as possible.<br>
";

$choix1mars1948m="Davai! (prestige +100, budget -$5/month)";
$choix1mars1948mtitle="Increases stalinism, you gain prestige but lose money";

$choix2mars1948m="We should be less presumptuous";
$choix2mars1948mtitle="Nothing happens";

$titremars1948m1="THE GREAT PLAN FOR THE TRANSFORMATION OF NATURE";
$textemars1948m1="
With such a plan, the entire Soviet industry can demonstrate its superiority over the West.<br>
Giant excavors leave our factories, able to remove 21m3 of earth at once!<br>
Everywhere, waters are being tamed, forests pushing deserts back and electricity production increasing to gargantuan output levels.<br>

";

$titremars1948m2="THE PLAN SHALL WAIT";
$textemars1948m2="
The Motherland is still being rebuilt after all!
";

// EVT N

$titremars1948n="THE MORALE IN BERLIN IS HIGH... FOR NOW";
$textemars1948n="
It seems the Berlin blockade will go on...<br>
We should increase the tonnage of deliveries because the city's reserves are running low.<br>
The airport facilities are insufficient to keep on with such significant air traffic: new runways must be built.<br>
The airlift costs are starting to weight heavily on our budget...<br>
The Berliners morale is still high and people begin to grow their own fruits and vegetables.

";

$choix1mars1948n="This is becoming complicated: let us give up (prestige -50)";
$choix1mars1948ntitle="You lose prestige but get back some budgetary capacity";

$choix2mars1948n="Let us continue the airlift (-$15/month)";
$choix2mars1948ntitle="The airlift budget increases";

$titremars1948n1="BERLIN ABANDONED";
$textemars1948n1="
The Soviets finally succeeded!<br>
The situation is Berlin was not sustainable anyway.
<br> You raised the humanitarian argument but everybody clearly reads between the lines: you wimped up!

";

$titremars1948n2="TEMPELHOF EXTENDED";
$textemars1948n2="
We will not give up: major construction works have been undertaken to extend Berlin runways and our allies are mobilising their own aviation to help the people of Berlin throughout this crisis.<br>
The free world realises the USA are a solid and trustworthy partner that will not let them down.

";

// EVT O

$titremars1948o="WINTER IS COMING!";
$textemars1948o="
While winter is coming, the situation of the people of Berlin becomes critical...<br>
In addition to the daily 5,000 tons of food we deliver, we will have to add 6,000 tons of coals to heat the town.<br>
The morale is still high in the streets and the people do not see us anymore as occupiers but as protectors.
<br>
However, should we inflict the population of Berlin the trial of a winter of restrictions?

";

$choix1mars1948o="This is becoming complicated: let us give up (prestige -100)";
$choix1mars1948otitle="You lose prestige but get back some budgetary capacity";

$choix2mars1948o="Let us continue the airlift (-$25/month)";
$choix2mars1948otitle="The airlift budget increases";

$titremars1948o1="BERLIN ABANDONED";
$textemars1948o1="
The Soviets finally succeeded!<br>
The situation is Berlin was not sustainable anyway.
<br> You raised the humanitarian argument but everybody clearly reads between the lines: you wimped up!

";

$titremars1948o2="BERLIN WILL HOLD FAST!";
$textemars1948o2="
We will not give up: Berlin airport facilities have been extended again and are now able to host more rotations.<br>
Our allies are impressed by our determination.

";

//EVT P

$titremars1948p="TOING AND FROING DOES NOT WANE";
$textemars1948p="
In Berlin, the Americans do not grow weaker! <br>
Airports were extended and even the Havel river is being used as runway for seaplanes.<br>
The daily tonnage that is delivered is simply amazing: over 5,000 tons according to our agents.<br>
The German are ceasing to consider the Americans as occupiers and began seing them as their protectors.<br>
This showdown we triggered seems to be more uncertain than we expected...

";

$choix1mars1948p="This is becoming complicated: let us give up (prestige -50)";
$choix1mars1948ptitle="You lose prestige but get back some budgetary capacity";

$choix2mars1948p="Let us continue the blockade";
$choix2mars1948ptitle="They will grow tired of this game, the share of the American airlift budget increases.";


$titremars1948p1="THE BLOCKADE IS LIFTED";
$textemars1948p1="
In Berlin, we gave up faced with the American determination.<br>
Our weakness was scrutinised by our Eastern European satellites: which conclusions will they draw from their observations?

";

$titremars1948p2="THE BLOCKADE GOES ON";
$textemars1948p2="
The airlift costs weight heavily on the American budget and winter is coming...<br>
Time is obviously on our side.

";

// EVT Q

$titremars1948q="WINTER IS HERE!";
$textemars1948q="
Now that winter is here, the situation is dire in West Berlin but East Germy also suffers from the blockade.<br>
Indeed, the current showdown with the USA deprives us from the Ruhr coal - that is vital to heat the country.<br>
Over time, our position does not seem that strong anymore...

";

$choix1mars1948q="This is becoming complicated: let us give up (prestige -100)";
$choix1mars1948qtitle="You lose prestige but get back some budgetary capacity";

$choix2mars1948q="Let us continue the blockade";
$choix2mars1948qtitle="They will grow tired of this game before we do";

$titremars1948q1="THE BLOCKADE IS LIFTED";
$textemars1948q1="
In Berlin, we gave up faced with the American determination.<br>
Our weakness was scrutinised by our Eastern European satellites: which conclusions will they draw from their observations?

";

$titremars1948q2="THE BLOCKADE GOES ON";
$textemars1948q2="
The airlift costs weight heavily on the American budget and winter is coming...<br>
Time is obviously on our side.

";




//EVT R

$titremars1948r="THE ISRAELI-ARAB WAR";
$textemars1948r="
Now that the British mandate over Palestine is over, the State of Israel is immediately proclaimed and the conflict between Arabs and Jews takes a new dimension.<br>
The Arab States in the region contest the new Jewish State and declared war to it.<br>
Will the Arab troops manage to coordinate their actions faced with united and determined Israelis?
";


// EVT S

$titremars1948s="AN UNPOPULAR PRESIDENT";
$textemars1948s="
Popularity of President Truman is in freefall since the beginning of the year; even people within his party wonder if he still is the right candidate...<br>
<br>After all, he is the man who used the A-bomb and set the Cold War with the Soviets in motion.<br>
His Republican rival, Thomas E. Dewey, seems to stand real chances to win the upcoming elections.
";

$choix1mars1948s="And the ballots decided that the winner is...";
$choix1mars1948stitle="What a suspense!";

$titremars1948s1="AND THE WINNER IS...";
$textemars1948s1="

";

$textetruman="HARRY TRUMAN !<br>
His victory seemed so unlikely that the Chicago Tribune newspaper prepared the day before ran \"Dewey Defeats Truman\" as a headline!

";

$textedewey="THOMAS E. DEWEY !<br>
Republicans craved their return to power since the 1930s!<br>
It was way over time to turn the page!<br>
As the President said himself: « You know that your future is still ahead of you! »<br>
The new President will come into office next January.";


// MODE FRANCE

// EVT T

$titremars1948t="STRIKE IN THE MINES!";
$textemars1948t="
The miners have been enthusiastic participants in the \"battle for coal\" to help the country recovering from the war.<br>
Their morale is now very low and the recent decrees abolishing the post-war established social rights are the straw that broke the camel's back.<br>
The iron miners and the metal workers have just stopped working and the coal miners are expected to be the next ones.<br>
For the Minister of the Interior, Jules Moch, this movement is unlike the others: there are many clues indicating that it is a well-prepared communist endeavour to trigger a showdown leading them to power.<br>
Jules Moch is decided to reopen the mine pits by force!<br>

";

$choix1mars1948t="Let the army liberate the mine pits! (-$10 / Prestige -10)";
$choix1mars1948ttitle="The order will be restored and the miners' movement will be broken but this showdown could last.";

$choix2mars1948t="Their demands are legitimate (budget -$5)";
$choix2mars1948ttitle="Will increase your social expenditures, the influence of the PCF will increase";


$titremars1948t1="CRUSHING";
$textemars1948t1="
Jules Moch decided not to take any risk: in addition to the new Compagnies Républicaines de Sécurité (CRS, Republican Security Companies), militaries called back from Germany are also present.<br>
We will also be able to test under real conditions our brand new antiriot equipments: lacrymal gas and water cannons.<bR>
This strike will be short-lived!

";

$titremars1948t2="NEGOCIATIONS";
$textemars1948t2="
The government and the population do not forget the efforts and sufferings endured by the miners during the occupation and during the battle for coal initiated after the war to rebuild the country.<br>
The decrees are withdrawn and a 26% wage increase is given to the strikers.<br>
The right is raging: this generosity will be heavy on the national budget in a time where all tightens their belts!<br>
";


//EVT U

$titremars1948u="AN INSURRECTIONARY STRIKE";
$textemars1948u="
Work in coal mines is totally stopped and the miners are ready to fight the finish with the forces of law and order.<br>
The fighting with the CRS eventually led to a first death.<br>
In reprisals, the CGT National Federation of the Underground and Similars voted unlimited strike on security measures for operations.<br>
Around the mine pits, barricades are built...<br>
For Jules Moch, this hardening confirms that a French \"Czech coup\" is ongoing.

";

$choix1mars1948u="Let us authorise live ammunations and call back the reservists (-$5 / Prestige -10)";
$choix1mars1948utitle="We must crush the red peril";

$choix2mars1948u="Too much blood has been shed already (-$5)";
$choix2mars1948utitle="The strike goes on and the influence of the PCF increases";

$titremars1948u1="AN INSURRECTIONARY STRIKE";
$textemars1948u1="
The mine pits are evacuated in spite of the fierce fight put by the miners who use everything they can find to bombard the forces of law.<br>
Molotov cocktails and attack grenades are even used in several occasions!<br>
In Firminy, an exchange of gunfires with a partisan group is to be deplored - what supports Minister Moch's decision.<br>
Curfew is instated in the corons (miners cottages) which are patrolled by the army.<br>
The North Africans miners are forced to resume work by the force of bayonets.
The movement, broken by force, tires...
";

$titremars1948u2="AN INSURRECTIONARY STRIKE";
$textemars1948u2="
The national - even global - solidarity organises itself to support the strikers.<br>
The dockers refuses to unload coal carrying ships and donations flows in from the entire world.<br>
Elisabeth, Queen Mother of Belgium, even welcomed the miners' children, as did many French households from the Parisian suburbs!<br>
By organising support protests marches, the CGT and the PCF are winning the hearts and they organise a strike that could last for a long time.
";




?>