<?php

$collectif="The civil society and the intelligentsia wake up";
$collectifdetail="Creation of a pro-US opposition and decrease in stability";


$partisansursstitle="Nationalists fool our troops and lead bold coups de main.";
$partisansurss="coup de main of nationalist partisans (prestige -10)";
$partisansurss2="USSR: coups de main of nationalist partisans (USSR prestige -10)";

$partisansurss3="USSR: harsh suppression of the nationalists (USSR prestige -10)";
$partisansursstitle4="Decrease in power of nationalist partisans";
$partisansurss4="Harsh suppression of the nationalists (USSR prestige -10)";

$effetaideusachine="American surpluses benefit to the Chinese National Revolutionary Army.";
$effetaideusachinedetail="The Chinese armed forces increase";

$finaideusachine="China: end of the American aid";
$finaideusachinedetail="China: end of the American aid";

$effetaideelas="Greece: Yugoslavia funds partisans! ";

$effetembargo="Protests against shortages generated by the embargo placed by ";
$effetembargodetail="Relations with the responsible superpower deteriorate and stability decreases";

$effetmarshall="Production outputs increase thanks to the Marshall Plan!";
$effetmarshalldetail="Increase in stability and relations with the USA improve";

$boomeconomique="Economic boom! The opposition lacks arguments.";
$boomeconomiquedetail="Increase in wealth and disappearance of non pro-US oppositions";

$manifsveteranschomeurs="Huge protests marches of unemployed veterans (Prestige USA -5)";
$manifsveteranschomeursdetail="Prestige -5";

$manifspenurie="Huge protests marches against shortages (Prestige USA -10)";
$manifspenuriedetail="Prestige -10";

$manifpacifiste="Huge pacifist protests marches (Prestige USA -5)";
$manifpacifistedetail="Prestige -5";

$manifspopulaires="Popular protests in favour of freedom of speech";
$manifspopulairesdetail="Decrease in stability: this event happens when the stalinism score is too low";

$passageouestatlete="An athlete crosses the Iron Curtain (USSR Prestige -5)";
$passageouestatletedetail="Loss in prestige: this event happens when the stalinism score is too high";

$passageouestintello="A famed intellectual crosses the Iron Curtain (USSR Prestige -15)";
$passageouestintellodetail="Loss in prestige: this event happens when the stalinism score is too high";

$passageouestscience="An eminent scientist crosses the Iron Curtain (USSR Prestige -5)";
$passageouestsciencedetail="Loss in prestige and technology transfer to the USA if they are lagging behind in terms of military research: this event happens when the stalinism score is too high";

$purgesmassives="Massive purges within the party (USSR prestige -10)";
$purgesmassivesdetail="Increase in stability; relations with Moscow improve and relations with Washington deteriorate:  this event happens when the stalinism score is high";

$grevemineursusa="General strike in the steel industry (USA Prestige -15)";
$grevemineursusadetail="Prestige -15";

$manifsinflation="Social movements against the high costs of living (USA Prestige -10)";
$manifsinflationdetail="Prestige -10";

$demandedemobilisation="Protest marches of mothers and wives for the return of their men (Prestige -10)";
$demandedemobilisationdetail="Prestige -10";

$versleneolithique="Deterioration of living conditions (USSR Prestige -10)";
$versleneolithiquedetail="Decrease in stability and wealth ";


$aidevnusa="Indochina: American aid to the French contingent";
$aidevnusadetail="French troops in Vietnam are reinforced and the stability of Vietnam increases if it is very weak";

$aidevmchine="Indochina: Chinese aid to the Viet Minh (+2)";
$aidevmchinedetail="Viet Minh grows stronger (+2)";

$aidekpchine="North Korea: massive Chinese material aid (armed forces +2)";
$aidekpchinedetail="North Korean armed forces +2";

$aideursschine="China: the Soviet aid supports the rebuilding of the country";
$aideursschinedetail="Increase in stability";

$aideursschinemil="China: reinforcement of the country\'s military capability (+3)";
$aideursschinemildetail="This is made possible by the Soviet aid";

$mccarthyhollywood="The Senate Permanent Subcommittee on Investigations accuses Hollywood ! (prestige -25)";
$mccarthyhollywooddetail="McCarthy strikes again! USA: loss of 25 prestige";

$mccarthyarmee="The Senate Permanent Subcommittee on Investigations accuses a general! (prestige -10)";
$mccarthyarmeedetail="McCarthy strikes again! USA: loss of 10 prestige";

$mccarthycitoyens="The Senate Permanent Subcommittee on Investigations accuses an eminant scientist! (prestige -5)";
$mccarthycitoyensdetail="McCarthy strikes again! USA: loss of 5 prestige";

$mccarthyretd="Leak of top secret US research files";
$mccarthyretddetail="The Soviets progress in their research on A/H bombs or on satellites";

$renffrvietnam="Indochina: France reinforces its contingent";
$renffrvietnamdetail="Increase in French armed forces in Vietnam";

$renffr="France: reinforcement of its military capacity";
$renffrdetail="Armed forces +2";



// MODE CHINE

$assistancesovietiquechinecoree="China: Soviet military and industrial aid";
$assistancesovietiquechinecoreedetail="As part of the Korean war, you gain 1% in military superpower score!";
$assistancesovietiquechinecoreedeux="China: Soviet help +$5";
$assistancesovietiquechinecoreetrois="China: Soviet help +$10";
$assistancesovietiquechinecoreedeuxdetail="As part of the Korean war, China benefits from a material aid from the Soviets";

$attaquebanditschine="China: bandits attack! (Prestige -5, -$5)";
$attaquebanditschinedetail="Bandits are ruining the country!";

$suppressionbanditschine="China: bandits have been punished! bandits: -";
$suppressionbanditschinedetail="The number of bandits diminshes";

$raidlimi="China: raid from Burma by Li Mi\'s irregulars (Prestige -5, -$5)";
$raidlimidetail="We will have to solve this problem!";


// 1953-1956

$finterrevierge="USSR: end of the Virgin Lands campaign";
$finterreviergedetail="End of the campaign";

$recolteabondante="USSR: plentiful harvest (Prestige +10)";
$recolteabondantedetail="Prestige +10";

$recolteexceptionnelle="USSR: plentiful harvest (Prestige +25)";
$recolteexceptionnelledetail="Prestige +25";

$kashmirprincess="China: technology trade with Western companies";
$kashmirprincessdetail="Superpower score +1%";

$reconstructionusa="USA: transition to peace economy";
$reconstructionusadetail="USA monthly budget increased by 5";

$deveconomiqueusa="USA: developpement of the economy";
$deveconomiqueusadetail="USA monthly budget increased by 5";

$egypterevolte5355="Egypte : Revolution !";
$egypterevolte5355detail="Army overthrow monarchy";

$aidefln="Algeria : FLN helped by arabic countries";
$aideflndetail="+2 armed forces for this guerilla";

$aideflnest="Algeria : FLN helped by socialist states";
$aideflnestdetail="+2 armed forces for this guerilla";

// 1957-1958

$dazibao1="China: massive workers strikes(prestige -5 / budget -$5)";
$dazibao1detail="Budget -$5, prestige -5";

$dazibao2="China: armed revolts in the countrysides (prestige -5 / budget -$10)";
$dazibao2detail="Budget -$10, prestige -5, increase in bandits strength";

$dazibao3="China: proliferation of mutiny in the army (prestige -5)";
$dazibao3detail="Very sharp increase in bandits strength";

$banditstibet="Tibet: the fight against counterrevolutionaries goes on (-5$)";
$banditstibetdetail="Tibetan bandits strength decreases by 1";

$grandbondbandits="China: starving bandits!";
$grandbondbanditsdetail="The regrouping of the Chinese population in people\'s communes cut the bandits from their supplies: their strength decreases";

// 1959-1962

$cornfrenzy="USRR: record corn production! (prestige USSR +10)";
$cornfrenzydetail="USRRprestige +10";

$passageouest="Berlin: significant volume of defections to the West (USSR prestige -25)";
$passageouestdetail="USSR prestige -25";

$tensionsinovov="USSR: tensions between the USSR and China";
$tensionsinovovdetail="Deterioration of the Soviet relations with China";

$tensionsinovov2="USSR: China gathers troops at its border with the USSR";
$tensionsinovov2detail="Very sharp deterioration of the Soviet relations with China";

$tensionsinovov3="USSR: relations at a standstill between Moscow and Beijing";
$tensionsinovov3detail="Sharp deterioration of the Soviet relations with China";

$survolu2="A U2 flies over the USSR: exceptional harvest of intel! (prestige USA +10)";
$survolu2ru="Gain in prestige";
$survolu2detail="USSR: American spy aeroplanes fly recklessly over our territory (Prestige URSS -10)";
$survolu2rudetail="Loss of prestige";

$emeutesraciales="USA: race riots (prestige -10)";
$emeutesracialesdetail="Loss of prestige";

$emeutesraciales2="USA: violent police suppression of a civil rights demonstration (prestige -15)";
$emeutesraciales2detail="Loss of prestige and increase of the civil rights contestation";

$kkk="USA: the Ku Klux Klan kills! (prestige -5)";
$kkkdetail="We live in the 20th century, how can such things still happen?";

$allianceprogres=": this country\'s economy is developing";
$allianceprogresdetail="This thanks to the Alliance for Progress: stability increases and the relations with the USA improve";


// 1963

$crisebonzes="Vietnam: demonstrations and Buddhist immolations";
$crisebonzesdetail="Stability decreases";

$konfrontasi="Borneo: increase of Indonesian commando infiltrations";
$konfrontasidetail="Indonesian armed forces +2";

$pistehochimin="Vietnam: Vietcong reinforcements";
$pistehochimindetail="Via the Ho Chi Minh trail: +";
$pistehochimindetail2="The Vietcong is active again in South Vietnam";

$dragonasiatique=": economic growth";
$dragonasiatiquedetail="Wealth increases by 1 and stability by 2!";

$aidechineVM="Vietnam: important Chinese military aid";
$aidechineVMdetail="Armed forces +";

$rollingmarche="North Vietnam: the bombings are disorganising the country";
$rollingmarchedetail="Who said Operation Rolling Thunder was useless? Stability and wealth decrease in North Vietnam";

$brejnev1="The economists notice the convergence between the Soviet and Western economies (prestige +10)";
$brejnev1detail="Well, a number of them do";

$brejnev2="USSR: increase in households consumption (prestige +5)";
$brejnev2detail="The time between order and delivery of a car is of 8 years: a proof that demand is booming!";

$brejnev3="USSR: increase in living standards in cities (prestige +5)";
$brejnev3detail="The time between order and delivery of a car is now above 10 years: will Moscow have traffic jams like in the West?!";

$brejnev4="Brezhnevian Cult: Brezhnev honoured again with the Order of Lenin (prestige -5)";
$brejnev4detail="The entire world is having au laugh";

$brejnev5="USSR: What would happen to a crocodile which swallow Brezhnev ?";
$brejnev5detail="He would shit medals for two weeks";

$brejnev6="Brezhnevian Cult: Brezhnev publishes his War Memoirs (prestige -5)";
$brejnev6detail="You see, he knows how to write!";

$brejnev7="Brezhnevian Cult: Brezhnev honoured with the Order of Victory (prestige -5)";
$brejnev7detail="Did he not already have this one?";

$brejnev8="Brezhnevian Cult: Brezhnev honoured with the Karl Marx gold medal (prestige -5)";
$brejnev8detail="Did he not already have this one?";

$brejnev9="Brezhnevian Cult: Brezhnev made Hero of the Soviet Union (prestige -5)";
$brejnev9detail="The entire world is having au laugh";

$liberman1=": economic growth";
$liberman1detail="Wealth and stability increase, Stalinism decreases (-2)";
$liberman2=": economic catch-up";
$liberman2detail="Stability increases, Stalinism decreases (-1)";
$liberman3=": is experimenting \"socialism with a human face\"";
$liberman3detail="Stalinism decreases (-1)";
$liberman4=": failure of the economic reforms";
$liberman4detail="Stability decreases";

$repriseoffensiveVM="Vietnam: North Vietnam is on the offensive anew";
$repriseoffensiveVMdetail="The war resumes";

// 1966

$detournallianceprogres=": developement of a kleptocracy around the American aid";
$detournallianceprogresdetail="Stability decreases and the country gains the trait Corrupted";

// MODE FRANCE

$grevesfrance="France: the CGT call to strike had a high turnout (-$5)";
$grevesfrancedetail="The PCF, feeling power slipping away of its hands, pressures the goverment";

$lareconstructionavance="France: the reconstruction of the country progresses!";
$lareconstructionavancedetail="+1% to your reconstruction score";

$hoahaoveste="Vietnam: alliance turnaround for the Hoa Hao";
$hoahaovestedetail="These lads are unpredictable";

$rebellesnationalistes="Nationalist rebels";

$pcempire=": the Communist party gathers the discontents";
$pcempiredetail="An opposition controlled by the USSR appears";

$rebellionempire=": rebels took up arms!";
$rebellionempiredetail="A nationalist guerrilla appears";

$greveempire=": railway workers strike";
$greveempiredetail="Stability decreases";

$grevesmineursfrance="France: an endless miners strike (-$5)";
$grevesmineursfrancedetail="They will grow tired... will they not?";

$caodaiveste="Vietnam: alliance turnaround for the Cao Dai";
$caodaivestedetail="These lads are unpredictable";

$binhxuyenveste="Vietnam: alliance turnaround for the Bình Xuyên militia";
$binhxuyenvestedetail="These lads are unpredictable";

$rc4a="End of the battle of Route Colonial 4: French victory!";
$rc4adetail="The Vietminh did not succeed in percing through the French lines";

$rc4b="End of the battle of Route Colonial 4: French tactical successes (Vietminh -1)(-$5)";
$rc4bdetail="The guerrilla strength decreases";

$rc4c="End of the battle of Route Colonial 4: French defeat (-25 prestige, -$5)";
$rc4cdetail="The Vietminh gains the trait Extraterritorial base";

$rc4d="End of the battle of Route Colonial 4: the fight is raging and its outcom is unpredictable (-$5)";
$rc4ddetail="Can France win?";

$aidechinoisevietminh="Indochina: Chinese aid to the Vietminh (+1)";
$aidechinoisevietminhdetail="The Vietminh gains +1 in strength";

$aidechinoisevietminhb="Indochina: Chinese aid to the Vietminh (+2 / Heavy weapons)";
$aidechinoisevietminhbdetail="The Vietminh gains +2 in strength";

$aideusindochine="American aid for the Indochina War (budget +$10)";
$aideusindochinedetail="We will use it to balance the national accounts";

//pertes débouchés commerciaux

$pertedebouchescommericaux="USA : the economy suffers from the lack of commercial opportunities in Western Europe";
$pertedebouchescommericauxdetail="US monthly budget -5$";

// Guerre d'algérie

$aideflnusa="Algeria : FLN helped by USA";
$aideflnusadetail="+1 armed forces for this guerilla";


//  année 70
$bombcambodgeusa="Cambodia: protest against American bombing on its territory.";
$bombcambodgeusadetail="Decrease in relations between the USA and Cambodia";

$eventostpol=" : increased trade with the West.";
$eventostpoldetail="Stability increases but Stalinism decreases 1";

$inflationetcrise=" : galloping inflation and economic crisis";
$inflationetcrisedetail="Decrease in stability, or even in wealth";

// 1976

$aidearabesarawi="Western Sahara: the Polisario front helped by an Arab country.";
$aidearabesarawidetail="The Libyans, or the Algerians, financed this guerrilla warfare (+1) ";

//1980

$creanciers=": the country announces it cannot no longer reimburse its creditors!";
$creanciersdetail="Stability (and sometimes even wealth) decreases";

$aidearabesiraq="Iraq: important financial support from the Gulf States";
$aidearabesiraqdetail="Stability +1 and armed forces +1";

$enleveliban="Lebanon: abduction of American citizens (USA prestige -5)";
$enlevelibandetail="They are said to be detained by a Shia militia";

$aidsaafghanistan="Aid from the Gulf monarchies to the Afghan guerrilla";
$aidsaafghanistandetail="Their champion (Hezb-e-Islami Gulbuddin) gains +1 in strength";

$aidpkafghanistan="Aid from Pakistan to the Afghan guerrilla";
$aidpkafghanistandetail="Its champion (Hezb-e-Islami Gulbuddin) gains +1 in strength";

$aidirafghanistan="Aid from Iran to the Afghan guerrilla";
$aidirafghanistandetail="Its champions (the Teheran's 8) gain +1 in strength";

$desertionafghanistan="Afghanistan: desertions are multiplying in the regular army";
$desertionafghanistandetail="Armed forces -1";

$basidjis="Iran: mass levy of Bassidjis";
$basidjisdetail="Armed forces +10, stability +1";

$fortifiraq="Iraq: military engineers build formidable defences";
$fortifiraqdetail="Stability +2";

$armesmodernesirak="Iraq: the country builds up its stock of modern weapons.";
$armesmodernesirakdetail="Armed forces +3";

// Guerre d'algérie

$aideflnusa="Algeria: the FLN is helped by the USA";
$aideflnusadetail="The guerrilla group strength is increased by 2";

$flnattaquesas="Algeria: violent FLN attacks against the Specialised Administrative Sections";
$flnattaquesasdetail="The number of SAS decreases by 1";

$aideflnest="Algeria: the FLN is helped by socialist States";
$aideflnestdetail="The guerrilla group strength is increased by 2";

$denoncetorturealgerie="Intellectuals denounce the use of torture in Algeria (prestige -5)";
$denoncetorturealgeriedetail="France loses 5 prestige points";

$pertedebouchescommericaux="USA: the economy suffers from the lack of outlets in Western Europe";
$pertedebouchescommericauxdetail="USA monthly budget -5";

$bataillefrontieres="Algeria: France has the upper hand in the battle of borders";
$bataillefrontieresdetail="The maxium strength of the FLN decreases by 1";

$instabilitegouvfrance="The French government collapsed once more...";
$instabilitegouvfrancedetail="This country is ungovernable, the risk of a coup has increased";

$ungroupesereconstitue="Afghanistan: a group of Mujahideen rebuilt its forces";
$ungroupesereconstituedetail="A guerrilla group that disappeared just reappeared: this can happen as long as Peshawar is used as a rear base by the Mujahideen";
$ungroupesereconstituedetailb="A guerrilla group that disappeared just reappeared: this can happen as long as Iran is used as a rear base by the Mujahideen";

$querellesmujahidins="Afghanistan: the Mujahideen groups are quareling between themselves";
$querellesmujahidinsdetail="One group decided to expend its territory at the expense of other Mujahideen.";

$mujahidinsattentistes="Afghanistan a group of Mujahideen rebuilds its forces";
$mujahidinsattentistesdetail="A group gains the trait Wait-and-see and gains +1 in strength";

$attentatnonattribueinteretsamericains="World: violent terrorist attack against American intrerests (USA prestige -5)";
$attentatnonattribueinteretsamericainsdetail="No group claimed to be responsible for this attack";

$attentatnonattribueinteretsamericainsattribue="World: violent terrorist attack against American intrerests  (USA prestige -5), surely funded by ";
$attentatnonattribueinteretsamericainsattribuedetail="This Rogue State denies but the array of clues speaks for itself: the relations of this country with the USA deteriorate by 3";

$emeutesnationalistescaucase=": nationalist riots";
$emeutesnationalistescaucasedetail="Stability -1, nationalism +1";

$reveilislamcaucase=": awakening of Islam";
$reveilislamcaucasedetail="Nationalism +1 , Stalinism -1";

$massacrepopulationsrussescaucase=": massacre of Russian people!";
$massacrepopulationsrussescaucasedetail=" Stability -2";

$massacreinterethniquecaucase=": inter-ethnic massacres";
$massacreinterethniquecaucasedetail="Stability -2, nationalism +2";

$reveilcitoyencaucase=": a nationalist party gathers supporters";
$reveilcitoyencaucasedetail="Nationalism +1 , Stalinism -1";

$manifnationalistepacifiquerss=": large pacific nationalist demonstration";
$manifnationalistepacifiquerssdetail="Nationalism +2";



?>